title = "璀璨星空"
baseURL = 'https://jerry011235.github.io/index.html'
languageCode = 'en-us'
theme = "hugo-blog-awesome"

# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable  Google Analytics, simply leave the field empty or remove the next line
#googleAnalytics = '' # G-MEASUREMENT_ID


# Enable emojis globally
enableEmoji = true

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30


[params]
  sitename = "璀璨星空"
  defaultColor = "light" # set default color mode: dark or light
  description = "Minimal Hugo blog theme with light and dark mode support"

[params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Debanwita Mahato"
  name = "Debanwita Mahato"
  description = "CS undergrad trying to get a foothold in Web Dev and Machine Learning(and Deep Learning). I dabble in generative coding for the kicks. Currently looking for an interesting opportunity for a summer/autumn internship."

[[params.socialIcons]]
name = "github"
url = "https://github.com/debanwita27"

[[params.socialIcons]]
name = "linkedin"
url = "http://www.linkedin.com/in/debanwita-mahato-8779431b8/"

[[params.socialIcons]]
name = "leetcode"
url = "https://www.leetcode.com/dm2711/"

[[params.socialIcons]]
name = "email"
url = "mailto:debanwita27@gmail.com"
